PREFIX test: <http://famo_test_namespace.org#>
PREFIX famo: <http://ontology.eil.utoronto.ca/famo#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX genprop: <http://ontology.eil.utoronto.ca/5087/1/1/GenericProperties/>

DELETE {
    ?x famo:occupiedBy ?z.
}
INSERT {
    ?x famo:occupiedBy ?y.
}
WHERE {
    ?rec1 famo:indicatesSubjectIn ?p;
          famo:hasInterpretation [famo:denotes ?x].
    ?rec2 famo:indicatesObjectIn ?p;
          famo:hasInterpretation [famo:denotes ?y].
    # property manifestation class name TBD
    ?p a famo:RoleOccupationRelation.
}