PREFIX test: <http://famo_test_namespace.org#>
PREFIX famo: <http://ontology.eil.utoronto.ca/famo#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX genprop: <http://ontology.eil.utoronto.ca/5087/1/1/GenericProperties/>
DELETE {
    #for now, this makes the most sense
    #in the future, we might generalize this to remove all references to the current interpretation and thus need to break up the overall process into two queries (one to delete/insert and one to insert where no prior interpretation exists)
    test:S3ID2 famo:hasinterpretation ?i_current.
    ?i_current famo:interpretationOf test:S3ID2.
    ?i_current famo:denotes ?o.
}
INSERT {
	test:S3ID2 famo:hasInterpretation 
            [famo:denotes test:DHID_ROLE_S1ID2].
}
WHERE {
    OPTIONAL {
        test:S3ID2 famo:hasinterpretation ?i_current.
    }
}