PREFIX test: <http://famo_test_namespace.org#>
PREFIX famo: <http://ontology.eil.utoronto.ca/famo#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX genprop: <http://ontology.eil.utoronto.ca/5087/1/1/GenericProperties/>
DELETE {
    test:S1ID2 famo:hasInterpretation ?i_current.
    ?i_current famo:interpretationOf test:S1ID2.
    ?i_current famo:denotes ?o.
}
WHERE {
        test:S1ID2 famo:hasInterpretation ?i_current.
    	?i_current famo:denotes ?o.

}