PREFIX test: <http://famo_test_namespace.org#>
PREFIX famo: <http://ontology.eil.utoronto.ca/famo#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
DELETE {
   test:DHID_ASSET_S1ID2 famo:hasSerialNumber ?serial.
}
INSERT {
    test:DHID_ASSET_S1ID2 famo:hasSerialNumber "A2"^^xsd:string.
}
WHERE {
    OPTIONAL {
        test:DHID_ASSET_S1ID2 famo:hasSerialNumber ?serial.
    }
}